In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
tokenizer = Tokenizer(oov_token='hmm')

In [3]:
vocabulary= ['go india',
'india india',
'hip hip hurray',
'jeetega bhai jeetega india jeetega',
'bharat mata ki jai',
'kohli kohli',
'sachin sachin',
'dhoni dhoni',
'modi ji ki jai',
'inquilab zindabad'
]

In [4]:
tokenizer.fit_on_texts(vocabulary)

In [5]:
tokenizer.word_index

{'hmm': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [6]:
sequences = tokenizer.texts_to_sequences(vocabulary)

In [7]:
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [8]:
from tensorflow.keras.utils import pad_sequences

In [17]:
sequences = pad_sequences(sequences, padding='post')

In [18]:
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

In [9]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [10]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [11]:
X_train[:5]

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [12]:
y_train[:5]

array([1, 0, 0, 1, 0])

In [13]:
X_train = pad_sequences(X_train, padding='post', maxlen=200)
X_test = pad_sequences(X_test, padding='post', maxlen=200)

In [14]:
X_train.shape

(25000, 200)

In [37]:
model = Sequential()

In [38]:
model.add(SimpleRNN(32, input_shape=(200,1), return_sequences=False, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.summary()

f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [40]:
model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 17ms/step - accuracy: 0.5002 - loss: 0.6933 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 17ms/step - accuracy: 0.4969 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.4997 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 20ms/step - accuracy: 0.5030 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6933
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.4991 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 19s 24ms/step - accuracy: 0.5023 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6932
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 25ms/step - accuracy: 0.4949 - loss: 0.6932 - val_accuracy: 0.5000 - val_loss: 0.6931
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 26s 33ms/step - accuracy: 0.4998 - loss: 0.6932 - 

In [41]:
model.predict(sequences)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


array([[0.45362   ],
       [0.4639605 ],
       [0.22488637],
       [0.14141673],
       [0.14241725],
       [0.3504556 ],
       [0.32904992],
       [0.3081156 ],
       [0.1114758 ],
       [0.15913315]], dtype=float32)

In [15]:
model2 = Sequential()
model2.add(Embedding(10000, output_dim=2, input_length=200))
model2.add(SimpleRNN(32, return_sequences=False))
model2.add(Dense(1, activation='sigmoid'))

f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model2.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
history = model2.fit(X_train, y_train, epochs=8, validation_data=(X_test, y_test))

Epoch 1/8


InvalidArgumentError: Graph execution error:

Detected at node sequential_1/embedding_1/GatherV2 defined at (most recent call last):
  File "C:\Users\ayyub\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main

  File "C:\Users\ayyub\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel_launcher.py", line 18, in <module>

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\kernelapp.py", line 739, in start

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\tornado\platform\asyncio.py", line 211, in start

  File "C:\Users\ayyub\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever

  File "C:\Users\ayyub\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once

  File "C:\Users\ayyub\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\kernelbase.py", line 519, in dispatch_queue

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\kernelbase.py", line 508, in process_one

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\kernelbase.py", line 400, in dispatch_shell

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\ipkernel.py", line 368, in execute_request

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\ipkernel.py", line 455, in do_execute

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\ipykernel\zmqshell.py", line 577, in run_cell

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3077, in run_cell

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3132, in _run_cell

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\async_helpers.py", line 128, in _pseudo_sync_runner

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3336, in run_cell_async

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3519, in run_ast_nodes

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3579, in run_code

  File "C:\Users\ayyub\AppData\Local\Temp\ipykernel_27588\2687200775.py", line 2, in <module>

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 399, in fit

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 241, in function

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 154, in multi_step_on_iterator

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 125, in wrapper

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 134, in one_step_on_data

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 59, in train_step

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\layers\layer.py", line 941, in __call__

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\ops\operation.py", line 59, in __call__

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\models\sequential.py", line 220, in call

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\models\functional.py", line 183, in call

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\ops\function.py", line 206, in _run_through_graph

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\models\functional.py", line 644, in call

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\layers\layer.py", line 941, in __call__

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\ops\operation.py", line 59, in __call__

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\layers\core\embedding.py", line 158, in call

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\ops\numpy.py", line 6193, in take

  File "f:\Learning\DL\Learning\Deep-Learning\ANN\venv\lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2589, in take

indices[0,23] = 14675 is not in [0, 10000)
	 [[{{node sequential_1/embedding_1/GatherV2}}]] [Op:__inference_multi_step_on_iterator_2319]