In [1]:
import numpy as np
import pandas as pd

In [5]:
def initialize_parameters(layer_dimension):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dimension)

    for i in range(1, L):
        parameters['w' + str(i)] = np.ones((layer_dimension[i-1], layer_dimension[i]))*0.1
        parameters['b' + str(i)] = np.zeros((layer_dimension[i], 1))

    return parameters

In [6]:
def linear_forward(X, W, b):

    Z = np.dot(W.T, X) + b

    return Z

In [7]:
initialize_parameters([2,2,1])

{'w1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'w2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [8]:
def L_layer_forward(X, parameters):

    A = X
    L = len(parameters) // 2

    for l in range(1, L+1):

        A_prev = A
        W = parameters['w' + str(l)]
        b = parameters['b' + str(l)]

        print("X" + str(l-1) + ": ", A_prev)
        print("W"+str(l) + ": ", W)
        print("b"+str(l) + ": ", b)
        print("--"*20)

        A = linear_forward(A_prev, W, b)
        print("A"+str(l)+": ", A)
        print("**"*20)

    return A,A_prev

In [19]:
X = np.array([[8,5],[8,9]])

In [20]:
X

array([[8, 5],
       [8, 9]])

In [25]:
y = np.array([[4, 8]])

In [26]:
y

array([[4, 8]])

In [23]:
parameters = initialize_parameters([2,2,1])

In [24]:
L_layer_forward(X, parameters)

X0:  [[8 5]
 [8 9]]
W1:  [[0.1 0.1]
 [0.1 0.1]]
b1:  [[0.]
 [0.]]
----------------------------------------
A1:  [[1.6 1.4]
 [1.6 1.4]]
****************************************
X1:  [[1.6 1.4]
 [1.6 1.4]]
W2:  [[0.1]
 [0.1]]
b2:  [[0.]]
----------------------------------------
A2:  [[0.32 0.28]]
****************************************


(array([[0.32, 0.28]]),
 array([[1.6, 1.4],
        [1.6, 1.4]]))

In [28]:
(y-np.array([[0.32, 0.28]]))**2    #Loss for the data

array([[13.5424, 59.5984]])